# Generated by Django 2.0.1 on 2018-06-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wikistore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.CharField(default='', max_length=50)),
                ('user', models.CharField(default='', max_length=50)),
                ('status', models.IntegerField(default=0)),
                ('wikititle', models.CharField(default='', max_length=200)),
                ('wikicontent', models.TextField(default='')),
                ('wikitag', models.CharField(default='', max_length=200)),
                ('wikiurl', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
