# Generated by Django 2.0.1 on 2018-06-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_wikistore_wikisummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikistore',
            name='update_user',
            field=models.CharField(default='', max_length=50),
        ),
    ]
