# Generated by Django 2.0.1 on 2018-06-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_wikistore_update_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikistore',
            name='update_time',
            field=models.CharField(default='', max_length=50),
        ),
    ]
