# Generated by Django 2.0.1 on 2018-06-01 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_wikistore_update_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wikistore',
            name='wikiurl',
        ),
    ]
