# Generated by Django 2.0.1 on 2018-03-27 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appname', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businame', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='busi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fanyi.Business'),
        ),
    ]
