# Generated by Django 2.0.1 on 2018-03-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanyi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='urlname',
            field=models.CharField(default=2, max_length=64),
            preserve_default=False,
        ),
    ]
