# Generated by Django 2.0.1 on 2018-03-29 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fanyi', '0002_application_urlname'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReqInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_ip', models.CharField(max_length=128)),
                ('trans_direct', models.CharField(max_length=20)),
                ('isfromzh', models.IntegerField()),
                ('req_text', models.CharField(max_length=2000)),
                ('result', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='reqinfo',
            name='user_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fanyi.UserInfo'),
        ),
    ]
