# Generated by Django 2.0.1 on 2018-03-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanyi', '0003_auto_20180329_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reqinfo',
            name='isfromzh',
            field=models.CharField(max_length=10),
        ),
    ]
