# Generated by Django 2.0.1 on 2018-03-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanyi', '0004_auto_20180329_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='reqinfo',
            name='c_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
