# Generated by Django 2.0.1 on 2018-04-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanyi', '0008_usertoapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='reqinfo',
            name='reqtype',
            field=models.CharField(default='xml', max_length=20),
            preserve_default=False,
        ),
    ]
