# Generated by Django 2.0.1 on 2018-05-23 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fanyi', '0011_auto_20180521_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='FyMonitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.CharField(default='', max_length=50)),
                ('start_time', models.CharField(default='', max_length=50)),
                ('end_time', models.CharField(default='', max_length=50)),
                ('user', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=0)),
                ('monitorip', models.CharField(default='', max_length=500)),
                ('monitoruser', models.CharField(default='', max_length=500)),
                ('monitorpassw', models.CharField(default='', max_length=500)),
                ('gpumem', models.TextField(default='')),
                ('gpumemused', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(db_index=True, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='fy_monitor',
        ),
        migrations.AddField(
            model_name='fymonitor',
            name='h',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fanyi.Host'),
        ),
    ]
