# Generated by Django 2.0.1 on 2018-05-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanyi', '0012_auto_20180523_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='passw',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='host',
            name='user',
            field=models.CharField(default='', max_length=500),
        ),
    ]
