# Generated by Django 2.0.1 on 2018-05-25 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanyi', '0013_auto_20180523_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fymonitor',
            name='start_time',
        ),
    ]
