# Generated by Django 2.0.1 on 2018-05-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanyi', '0014_remove_fymonitor_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
