# Generated by Django 2.0.1 on 2018-07-09 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fanyi', '0018_auto_20180626_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiffContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.CharField(default='', max_length=50)),
                ('user', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=0)),
                ('errorlog', models.TextField(default='')),
                ('diff_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fanyi.FyDiff')),
            ],
        ),
    ]
