# Generated by Django 2.0.1 on 2018-07-09 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanyi', '0022_remove_diffcontent_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diffcontent',
            old_name='content',
            new_name='diff_content',
        ),
    ]
