# Generated by Django 2.0.1 on 2018-07-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanyi', '0025_fydiff_diffnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='fydiff',
            name='isfromzh',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='fydiff',
            name='trans_direct',
            field=models.CharField(default='', max_length=20),
        ),
    ]
