# Generated by Django 2.0.1 on 2018-07-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanyi', '0026_auto_20180712_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fydiff',
            old_name='trans_direct',
            new_name='fromlan',
        ),
        migrations.AddField(
            model_name='fydiff',
            name='tolan',
            field=models.CharField(default='', max_length=20),
        ),
    ]
