# Generated by Django 2.0.1 on 2018-07-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanyi', '0027_auto_20180712_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='fydiff',
            name='lan_sel',
            field=models.CharField(default='', max_length=10),
        ),
    ]
