# Generated by Django 2.0.1 on 2018-07-16 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fanyi', '0028_fydiff_lan_sel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FyXmlDiff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.CharField(default='', max_length=50)),
                ('start_time', models.CharField(default='', max_length=50)),
                ('end_time', models.CharField(default='', max_length=50)),
                ('user', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=0)),
                ('errorlog', models.TextField(default='')),
                ('testtag', models.CharField(default='', max_length=500)),
                ('finished', models.IntegerField(default=0)),
                ('diffnum', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='XmlDiffContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.CharField(default='', max_length=50)),
                ('user', models.CharField(max_length=50)),
                ('diff_content', models.TextField(default='')),
                ('diff_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fanyi.FyDiff')),
            ],
        ),
    ]
