# Generated by Django 2.0.1 on 2018-07-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanyi', '0029_fyxmldiff_xmldiffcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='fyxmldiff',
            name='base_url',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='fyxmldiff',
            name='test_url',
            field=models.CharField(default='', max_length=500),
        ),
    ]
