# Generated by Django 2.0.1 on 2018-07-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanyi', '0030_auto_20180716_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='fyxmldiff',
            name='queryip',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='fyxmldiff',
            name='querypassw',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='fyxmldiff',
            name='querypath',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='fyxmldiff',
            name='queyruser',
            field=models.CharField(default='', max_length=500),
        ),
    ]
