# Generated by Django 2.0.1 on 2018-08-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanyi', '0036_auto_20180803_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='ip',
            field=models.GenericIPAddressField(db_index=True),
        ),
    ]
