# Generated by Django 2.0.1 on 2018-04-29 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webqw', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webqwqps',
            name='just_run_base',
        ),
        migrations.RemoveField(
            model_name='webqwqps',
            name='just_run_test',
        ),
    ]
