# Generated by Django 2.0.6 on 2018-06-22 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fanyi', '0016_host_runningpid'),
        ('webqw', '0003_auto_20180509_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReqInfo_QW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_ip', models.CharField(max_length=128)),
                ('reqtype', models.CharField(max_length=20)),
                ('exp_id', models.CharField(max_length=8)),
                ('req_text', models.CharField(max_length=2000)),
                ('result', models.CharField(max_length=2000)),
                ('c_time', models.DateTimeField(auto_now=True)),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fanyi.UserInfo', to_field='user_name')),
            ],
        ),
    ]
