# Generated by Django 2.0.6 on 2018-07-31 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webqw', '0004_reqinfo_qw'),
    ]

    operations = [
        migrations.AddField(
            model_name='webqwqps',
            name='query_ip',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='webqwqps',
            name='query_path',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='webqwqps',
            name='query_pwd',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='webqwqps',
            name='query_user',
            field=models.CharField(default='', max_length=50),
        ),
    ]
