# Generated by Django 2.0.6 on 2018-07-31 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webqw', '0005_auto_20180731_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webqwqps',
            name='press_expid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='webqwqps',
            name='press_qps',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='webqwqps',
            name='press_time',
            field=models.IntegerField(default=30),
        ),
    ]
