# Generated by Django 2.0.6 on 2018-07-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webqw', '0006_auto_20180731_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webqwqps',
            name='press_expid',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='webqwqps',
            name='press_qps',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='webqwqps',
            name='press_rate',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='webqwqps',
            name='press_time',
            field=models.IntegerField(blank=True),
        ),
    ]
