# Generated by Django 2.0.6 on 2018-08-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webqw', '0008_auto_20180801_1110'),
    ]

    operations = [
        migrations.DeleteModel(
            name='webqwlongdiff',
        ),
        migrations.AddField(
            model_name='webqwqps',
            name='query_ip',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='webqwqps',
            name='query_path',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='webqwqps',
            name='query_pwd',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='webqwqps',
            name='query_user',
            field=models.CharField(default='', max_length=50),
        ),
    ]
