# Generated by Django 2.0.6 on 2018-08-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webqw', '0009_auto_20180801_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='webqwqps',
            name='diff_content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='webqwqps',
            name='press_qps',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='webqwqps',
            name='press_time',
            field=models.IntegerField(default=0),
        ),
    ]
