# Generated by Django 2.0.1 on 2018-04-28 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webqo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webqoqps',
            name='base_cpu_performance',
        ),
        migrations.RemoveField(
            model_name='webqoqps',
            name='exceptions',
        ),
        migrations.RemoveField(
            model_name='webqoqps',
            name='force_update_base_svn',
        ),
        migrations.RemoveField(
            model_name='webqoqps',
            name='force_update_test_svn',
        ),
        migrations.RemoveField(
            model_name='webqoqps',
            name='if_startmem',
        ),
        migrations.RemoveField(
            model_name='webqoqps',
            name='is_freeze',
        ),
        migrations.RemoveField(
            model_name='webqoqps',
            name='probe_result',
        ),
        migrations.RemoveField(
            model_name='webqoqps',
            name='regression_test_result',
        ),
        migrations.RemoveField(
            model_name='webqoqps',
            name='stress_test_cost',
        ),
        migrations.RemoveField(
            model_name='webqoqps',
            name='stress_test_cpu',
        ),
        migrations.RemoveField(
            model_name='webqoqps',
            name='stress_test_heap',
        ),
        migrations.RemoveField(
            model_name='webqoqps',
            name='stress_test_memory',
        ),
        migrations.RemoveField(
            model_name='webqoqps',
            name='stress_test_qps',
        ),
        migrations.RemoveField(
            model_name='webqoqps',
            name='test_cpu_performance',
        ),
        migrations.RemoveField(
            model_name='webqoqps',
            name='webqo_compatibility',
        ),
    ]
