# Generated by Django 2.0.1 on 2018-05-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webqo', '0003_auto_20180429_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='webqoqps',
            name='press_rate',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
