# Generated by Django 2.0.1 on 2018-05-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webqo', '0005_auto_20180502_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webqoqps',
            name='press_expid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='webqoqps',
            name='press_rate',
            field=models.FloatField(),
        ),
    ]
