# Generated by Django 2.0.1 on 2018-05-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webqo', '0006_auto_20180502_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='webqoqps',
            name='testtag',
            field=models.CharField(default='', max_length=500),
        ),
    ]
