# Generated by Django 2.0.6 on 2018-06-22 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fanyi', '0016_host_runningpid'),
        ('webqo', '0007_webqoqps_testtag'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReqInfo_QO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_ip', models.CharField(max_length=128)),
                ('exp_id', models.CharField(max_length=128)),
                ('query_from', models.CharField(max_length=4)),
                ('query', models.CharField(max_length=2000)),
                ('result', models.CharField(max_length=2000)),
                ('c_time', models.DateTimeField(auto_now=True)),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fanyi.UserInfo', to_field='user_name')),
            ],
        ),
    ]
