# Generated by Django 2.0.6 on 2018-06-22 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webqo', '0008_reqinfo_qo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reqinfo_qo',
            old_name='query',
            new_name='req_text',
        ),
    ]
