# Generated by Django 2.0.6 on 2018-06-22 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webqo', '0009_auto_20180622_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reqinfo_qo',
            old_name='req_text',
            new_name='query',
        ),
    ]
