from django.db import models

# Create your models here.
class webqoqps(models.Model):
    create_time = models.CharField(max_length=50, default="")
    start_time = models.CharField(max_length=50, default="")
    end_time = models.CharField(max_length=50, default="")
    user = models.CharField(max_length=50)
    status = models.IntegerField(default=0)
    step =  models.IntegerField(default=-1)
    testitem = models.IntegerField(default=0)
    newdataip = models.CharField(max_length=500, default="")
    newdatauser = models.CharField(max_length=500, default="")
    newdatapassw = models.CharField(max_length=500, default="")
    newdatapath = models.CharField(max_length=500, default="")
    newconfip = models.CharField(max_length=500, default="")
    newconfuser = models.CharField(max_length=500, default="")
    newconfpassw = models.CharField(max_length=500, default="")
    newconfpath = models.CharField(max_length=500, default="")
    runningIP = models.CharField(max_length=50, default="")
    testsvn = models.TextField(default="")
    basesvn = models.TextField(default="")
    errorlog = models.TextField(default="")
    cost_test = models.TextField(default="")
    cost_base = models.TextField(default="")
    test_cpu_performance = models.TextField(default="")
    base_cpu_performance = models.TextField(default="")
    regression_test_result = models.TextField(default="")
    webqo_compatibility = models.TextField(default="")
    probe_result = models.TextField(default="")
    stress_test_cpu = models.TextField(default="")
    stress_test_cost = models.TextField(default="")
    stress_test_qps = models.TextField(default="")
    stress_test_heap = models.TextField(default="")
    stress_test_memory = models.TextField(default="")
    exceptions = models.TextField(default="")
    is_freeze = models.BooleanField(default=False)
    if_startmem = models.BooleanField(default=True)
    just_run_test = models.BooleanField(default=False)
    just_run_base = models.BooleanField(default=False)
    force_update_test_svn = models.IntegerField(default=0)
    force_update_base_svn = models.IntegerField(default=0)
    press_qps = models.IntegerField()
    press_time = models.IntegerField()